### ISSUE TITLE
Features produce invalid geojson

### ISSUE THREAD

**Issue by rshura** [tidwall/geojson#10]
Apparently, `Feature` object is supposed to have both `geometry` and `properties`, according to the spec: https://tools.ietf.org/html/rfc7946#section-3.2

Currently, feature JSON is lacking properties, which makes it invalid. This makes the returned JSON unusable in e.g. geojson.io

The proposed fix is in https://github.com/tidwall/geojson/pull/9

**Comment by tidwall** [comment]
Looks good. I added an extra test and merged the PR.
