### ISSUE TITLE
Add MarshalJSON to geojson.Object

### ISSUE THREAD

**Issue by kruftmeister** [tidwall/geojson#7]
It would be really great to make `geojson.Object` Marshaler again. :)  We're using it (since the package was part of tile38) as a field of other types, which we often need to marshal to JSON. We now moved from tile38/geojson to the standalone one and took me a while to find out that geojson.Object is no longer a Marshaler.

**Comment by tidwall** [comment]
Thanks for PR. I just merged it moments ago!
